#!/usr/bin/env bash
# why you no love me 
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" exit SIGINT

mkdir -p var/run
echo "$$" > var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
