#!/usr/bin/env bash
#This script prints names, use ids and home directory path from the file
#+ '/etc/passwd
file="/etc/passwd"
while read -r line;
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "$file"
