#!/usr/bin/env bash
#This script about a user based on their story
while IFS= read -r line;
do
	Username=$(echo "$line" | cut -d ":" -f 1)
	Password=$(echo "$line" | cut -d ":" -f 2)
	UserID=$(echo "$line" | cut -d ":" -f 3)
	GroupID=$(echo "$line" | cut -d ":" -f 4)
	Home=$(echo "$line" | cut -d ":" -f 6)
	Shell=$(echo "$line" | cut -d ":" -f 6)

	echo "The user $Username is part of the $GroupID gang, lives in $Home and rides $Shell. $UserID's place is protected by the passcode $Password, more info about the user here: $UserID"

done < "/etc/passwd"
